---
- name: "Disabling and clean tmp."
  shell: |
    sudo sed -i 's/D/#&/' /usr/lib/tmpfiles.d/tmp.conf

- name: "Add After=dbus.service to open-vm-tools"
  shell: |
    sudo sed -i '/^After=vgauthd.service/a\After=dbus.service' /lib/systemd/system/open-vm-tools.service

- name: "Preparing cloud-init."
  shell: |
    rm -rf /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg
    rm -rf /etc/cloud/cloud.cfg.d/99-installer.cfg
    rm -rf /etc/netplan/00-installer-config.yaml
    echo "disable_vmware_customization: false" >> /etc/cloud/cloud.cfg
    echo "datasource_list: [ VMware, OVF, None ]" > /etc/cloud/cloud.cfg.d/90_dpkg.cfg

- name: "Modifying GRUB."
  shell: |
    sed -i -e "s/GRUB_CMDLINE_LINUX_DEFAULT=\"\(.*\)\"/GRUB_CMDLINE_LINUX_DEFAULT=\"\"/" /etc/default/grub
    update-grub

- name: Set hostname to localhost
  hostname:
    name: localhost

# Fix cloudinit dns server not being applied
- name: "Fixing resolv.conf"
  shell: |
    sudo unlink /etc/resolv.conf
    sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
    sudo systemctl restart systemd-resolved.service
    sudo netplan apply
