vcenter_datacenter = "datacenter1"
vcenter_datastore = "datastore2-hdd"
vcenter_host = "192.168.1.201"
vcenter_folder = "VMs-template"
tools_upgrade_policy = true
remove_cdrom = true
vm_guest_os_type = ubuntu64Guest
vm_name = "ubuntu-20.04-base-template"
vm_cpu_sockets = 2
vm_cpu_cores = 2
vm_mem_size = 4096
vm_disk_size = 30720
vcenter_network = "VM Network"
vm_network_card = "vmxnet3"
iso_paths = ["[datastore2-hdd] vm-iso/ubuntu-20.04.5-live-server-amd64.iso"]
http_directory = "http"
vm_boot_order = "disk,cdrom"
vm_boot_wait = "2s"